[package]
name = "nexis"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bootloader = "0.11.0"
uart_16550 = "0.2.0"
spin = "0.9"
lazy_static = "1.4"

[package.metadata.bootimage]
target = "x86_64-nexis.json"
