[package]
name = "ironveil"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
tui = "0.19"          
rand = { version = "0.8", features = ["std", "small_rng"] }
chrono = "0.4"
dirs = "5"